//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbRest.Suschnosti
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public int menu_id { get; set; }
        public string kategoriya { get; set; }
        public string nazvanie_bluda { get; set; }
        public string ingredient { get; set; }
        public double cena { get; set; }
    }
}
