//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbRest.Suschnosti
{
    using System;
    using System.Collections.Generic;
    
    public partial class polzovateli
    {
        public int polzovatel_id { get; set; }
        public string imya_polzovatelya { get; set; }
        public string telefon { get; set; }
        public string login { get; set; }
        public string parol { get; set; }
    }
}
