//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbRest.Suschnosti
{
    using System;
    using System.Collections.Generic;
    
    public partial class postavchik
    {
        public int postavchik_id { get; set; }
        public string nazvanie_postavchika { get; set; }
    }
}
