//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbRest.Suschnosti
{
    using System;
    using System.Collections.Generic;
    
    public partial class sotrudniki
    {
        public int sotrudnik_id { get; set; }
        public string imya_sotrudnika { get; set; }
        public string login { get; set; }
        public string parol { get; set; }
        public Nullable<int> role_polzovatel { get; set; }
    
        public virtual role role { get; set; }
    }
}
